settings:
   database-connect: false
   use-perm-system: false
   server-name:
   server-id: 1
   join-broadcast: false
   websync:
      active: false
      url: http://quartzcraft.co.uk/api.php
      key: API_Key
database:
   core:
      host: 127.0.0.1
      database: QuartzCore
      username: root
      password: Database1



   