database:
   core:
      host: 
      database: 
      username: 
      password: 
   website:
      host: 
      database: 
      username:
      password:
   log:
      host:
      database:
      username:
      password:
settings:
   join-broadcast: false

   