database:
   core:
      host: 
      database: 
      username: 
      password: 
   website:
      host: 
      database: 
      username:
      password:
settings:
   join-broadcast: false
   primary-promote-command: pex user <user> group set <group>
   primary-promote-command: pex user <user> group remove <group>
   secondary-promote-command: pex user <user> group add <group>

   