database:
   core:
      host: 
      database: 
      username: 
      password:
   log:
      host:
      database:
      username:
      password:
settings:
   database-connect: false
   server-name:
   server-id:
   join-broadcast: false
   websync:
      active: false
      url: http://quartzcraft.co.uk/api.php
      key: API_Key


   