name: QuartzCore
version: 1.6.4
author: The QuartzCraft Team! SoulPunisher, mba2012 and nfell2009!
website: http://www.quartzcraft.co.uk/
main: uk.co.quartzcraft.QuartzCore

commands:
   quartz:
      description: Runs quick checks.
      usage: /quartz
      permission: QCC.quartz
      permission-message: Unknown Command. Type "help" for help.
   register:
      description: Registers a player
      usage: /register
      permission: QCC.register
      permission-message: Unknown Command. Type "help" for help.
   test:
      description: Test command, set to test whatever.
      usage: /test
      permission: QCC.dev.test
      permission-message: Unknown Command. Type "help" for help.
   m:
      description: Switches player gamemode between 0 and 1.
      usage: /m
      permission: QCC.admin.m
      permission-message: Unknown Command. Type "help" for help.
   list:
      description: Lists online players.
      usage: /list
      permission: QCC.list
      permission-message: Unknown Command. Type "help" for help.
      alias: who
   go:
      description: Teleports you to a player.
      usage: /go
      permission: QCC.go
      permission-message: Unknown Command. Type "help" for help.
   get:
      description: Teleports a player to you.
      usage: /get
      permission: QCC.get
      permission-message: Unknown Command. Type "help" for help.
   cleardrops:
      description: Cears all drops of the ground.
      usage: /cleardrops
      permission: QCC.admin.drops
      permission-message: Unknown Command. Type "help" for help.
      alias: t, te
   donate:
      description: Tells you how to donate.
      usage: /donate
      permission: QCC.donate
      permission-message: Unknown Command. Type "help" for help.
   chat:
      description: Basic chat command
      usage: /chat
      permission: QCC.chat
      permission-message: Unknown Command. Type "help" for help.
      alias: ch
   mood:
      description: Changes mood
      usage: /mood
      permission: QCC.mood
      permission-message: Unknown Command. Type "help" for help.
      alias: mo, md, moo
   team:
      description: Basic team command
      usage: /team
      permission: QCC.team
      permission-message: Unknown Command. Type "help" for help.
      alias: t, te
   report:
      description: Report a rule breaker
      usage: /report
      permission: QCC.report
      permission-message: Unknown Command. Type "help" for help.
