name: QuartzCore
version: 20160409a
author: The QuartzCraft Team! mba2012, SoulPunisher & nfell2009
website: http://quartzcraft.co.uk/
main: uk.co.quartzcraft.core.QuartzCore
loadbefore: [QuartzKingdoms]

commands:
   quartz:
      description: Runs quick checks.
      usage: /quartz
      permission: QCC.quartz
      default: op
      permission-message: Unknown Command. Visit the QuartzCraft Wiki for help.
   register:
      description: Begins the website registration process.
      usage: /register
      permission: QCC.register
      default: op
      permission-message: Unknown Command. Visit the QuartzCraft Wiki for help.
Permissions:
   QCC.*:
      description: Allows access to all QCC permissions.
      default: op
      children:
         QCC.promo: true
         QCC.report: true
         QCC.get: true
         QCC.go: true
         QCC.admin.m: true
         QCC.quartz: true
   QCC.tp.*:
      description: Allows access to all QCC tp permissions.
      default: op
      children:
         QCC.tp.get: true
         QCC.tp.go: true
   QCC.announce.*:
      description: Allows access to all QCC announce permissions.
      default: op
      children:
         QCC.announce: true
         QCC.announce.title: true
         QCC.announce.bar: true
   QCC.chat.*:
      description: Allows access to all QCC chat permissions.
      default: op
      children:
         QCC.chat.filterBypass: true
   QCC.chat.filterBypass:
      description: Allows bypass of the chat filter.
      default: op
   QCC.test:
      description: Test permission.
      default: op
   QCC.reload:
      description: Gives a player permission to perform the reload command.
      default: op
   QCC.report:
      description: Gives a player permission to perform the report command.
      default: op
   QCC.promo:
      description: Gives a player permission to perform the promo command.
      default: op
   QCC.pinfo:
      description: Gives a player permission to perform the pinfo command.
      default: op
   QCC.alerts:
      description: Gives a player permission to perform the alerts command.
      default: op
   QCC.bypassmax:
      description: Gives a player permission to perform the alerts command.
      default: op